server:
  port: 8083

spring:
  application:
    name: money-order-service

  datasource:
    url: jdbc:h2:mem:rmo
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# =========================
# JWT CONFIG
# =========================
jwt:
  secret: rmo-secret-key-rmo-secret-key-rmo-secret-key

# =========================
# MONEY ORDER CONFIG
# =========================
rmo:
  per-check-limit: 5000
  max-orders: 20
  fee-amount: 500
  compliance-threshold: 100000

# =========================
# AGENT LIMIT SERVICE
# =========================
agent:
  limit:
    service:
      url: http://localhost:8082
